import {
  ArrowRight,
  ArrowLeft,
  Check,
  ChevronsUpDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Copy,
  Edit,
  ExternalLink,
  File,
  HelpCircle,
  Home,
  Loader2,
  Mail,
  Menu,
  MessageSquare,
  Moon,
  Plus,
  PlusCircle,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Sun,
  Trash,
  User,
  Workflow,
  Calendar,
  Coins,
  List,
  FilePlus,
  Download,
  Info,
  CreditCard,
  X,
  Star,
} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  check: Check,
  chevronDown: ChevronsUpDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  menu: Menu,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  star: Star,
  trash: Trash,
  user: User,
  calendar: Calendar,
  coins: Coins,
  list: List,
  filePlus: FilePlus,
  download: Download,
  info: Info,
  creditCard: CreditCard,
};

export { Icons };


